sudo: false
language: node
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: prime-bridge-220106
  default: true
  no_promote: true
  on:
    all_branches: master
before_install:
- openssl aes-256-cbc -K $encrypted_474036f87d1c_key -iv $encrypted_474036f87d1c_iv
  -in client-secret.json.enc -out client-secret.json -d
install:
- gcloud config set project prime-bridge-220106
- gcloud -q components update gae-python
# Install the Python dependencies
- pip install -r requirements.txt -t lib/
script:
# [START deploy]
# Deploy the app
- gcloud -q preview app deploy app.yaml --promote
